apiVersion: apps/v1
kind: Deployment
metadata:
  name: TimingOracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TimingOracle
  template:
    metadata:
      labels:
        app: TimingOracle
    spec:
      containers:
        - name: webapp
          image: ""
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
