apiVersion: apps/v1
kind: Deployment
metadata:
  name: JWTCafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JWTCafe
  template:
    metadata:
      labels:
        app: JWTCafe
    spec:
      containers:
        - name: webapp
          image: ""
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
