apiVersion: apps/v1
kind: Deployment
metadata:
  name: UseAfterFree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UseAfterFree
  template:
    metadata:
      labels:
        app: UseAfterFree
    spec:
      containers:
        - name: webapp
          image: ""
          ports:
            - containerPort: 1337
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
